# Cloudflare Workers configuration for Dextract-fi API
name = "dextract-api"
main = "dist/main.js"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]  # Moved to proper section

# Configure build
[build]
command = "pnpm run build"
watch_dir = "src"

# Configure dev environment
[dev]
port = 8787
local_protocol = "http"

# Production environment
[env.development]
workers_dev = true
name = "dextract-api-dev"

# Production environment
[env.production]
workers_dev = false
name = "dextract-api-prd"

# Routes configuration
[[routes]]
pattern = "api.dextract.xyz/*"
zone_name = "dextract-api"

# Environment variables
[vars]
NODE_ENV = "development"
ALLOWED_ORIGINS = "https://dextract.xyz,https://app.dextract.xyz"